### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by gangaiamaran**

### CODE REVIEW

**Comment by oscarmorrison** [comment]
@sheldonvaughn any update on this? Blocking us for a laravel-10 upgrade. Thanks 🙌

**Comment by sheldonvaughn** [comment]
@oscarmorrison @gangaiamaran we've release v3.1.0 to enable usage with Laravel 10 - please let us know if you run into any issues.

**Comment by oscarmorrison** [comment]
Thanks so much @sheldonvaughn love your work @gangaiamaran 🙌

**Comment by gangaiamaran** [comment]
Thankyou 🥰 @oscarmorrison @sheldonvaughn

**Pull request closed without merging**
